# Generated by Django 5.1.4 on 2025-01-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membre", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="membre",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="membre",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
