# Generated by Django 5.1.3 on 2025-01-22 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membre", "0002_membre_age_membre_date_creation_membre_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membre",
            name="email",
        ),
        migrations.AddField(
            model_name="membre",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salon_name", models.CharField(max_length=100)),
                ("date_creation", models.DateTimeField(auto_now=True, null=True)),
                (
                    "salon_users",
                    models.ManyToManyField(
                        related_name="accessible_salons", to="membre.membre"
                    ),
                ),
            ],
        ),
    ]
