# Generated by Django 5.1.3 on 2025-01-22 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membre", "0003_remove_membre_email_membre_user_salon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="salon",
            old_name="salon_name",
            new_name="nom",
        ),
        migrations.RemoveField(
            model_name="salon",
            name="salon_users",
        ),
        migrations.AddField(
            model_name="salon",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salon",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="authorized_salons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
